apiVersion: apps/v1
kind: Deployment
metadata: { name: producer }
spec:
  replicas: 1
  selector: { matchLabels: { app: producer } }
  template:
    metadata: { labels: { app: producer } }
    spec:
      containers:
        - name: producer
          image: ecr_repos/hep-streaming:latest
          command: ["python", "producer.py"]
          env:
            - { name: KAFKA_BROKERS,   value: "msk-brokers" }
            - { name: DATA,            value: "HIGGS_sample.csv" }
            - { name: EVENTS_PER_SEC,  value: "500" }