name: ci-cd

on:
  push:
    branches: [main]
  workflow_dispatch:            

jobs:
  validate:                     
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Validate Terraform
        working-directory: infra
        run: |
          terraform init -backend=false
          terraform validate

  deploy:                      
    if: github.event_name == 'workflow_dispatch'
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - run: pip install numpy -t lambdas/inference/
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform apply
        working-directory: infra
        run: |
          terraform init
          terraform apply -auto-approve